name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Install ninja
      run: pip install ninja
    - name: Install meson
      run: pip install meson
    - name: Setup project build directory
      run: meson setup build
    - name: Compile project
      run: meson compile -C build
    - name: Run tests
      run: meson test -C build
